# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import google.protobuf.empty_pb2 as google_dot_protobuf_dot_empty__pb2
import grpc

import service_pb2 as service__pb2


class RosBridgeServiceStub(object):

    def __init__(self, channel):
        """Constructor.

        Args:
          channel: A grpc.Channel.
        """
        self.reset = channel.unary_unary(
            '/rosbridge_service.RosBridgeService/reset',
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
        self.reportTwistData = channel.stream_unary(
            '/rosbridge_service.RosBridgeService/reportTwistData',
            request_serializer=service__pb2.TwistData.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )


class RosBridgeServiceServicer(object):

    def reset(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def reportTwistData(self, request_iterator, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RosBridgeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'reset': grpc.unary_unary_rpc_method_handler(
            servicer.reset,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
        'reportTwistData': grpc.stream_unary_rpc_method_handler(
            servicer.reportTwistData,
            request_deserializer=service__pb2.TwistData.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'rosbridge_service.RosBridgeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
