# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import google.protobuf.empty_pb2 as google_dot_protobuf_dot_empty__pb2
import google.protobuf.wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2
import grpc

import rosbridge_service_pb2 as rosbridge__service__pb2


class RosBridgeServiceStub(object):

    def __init__(self, channel):
        """Constructor.

        Args:
          channel: A grpc.Channel.
        """
        self.writeTwistValue = channel.unary_unary(
            '/rosbridge_service.RosBridgeService/writeTwistValue',
            request_serializer=rosbridge__service__pb2.TwistValue.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
        self.streamTwistValues = channel.stream_unary(
            '/rosbridge_service.RosBridgeService/streamTwistValues',
            request_serializer=rosbridge__service__pb2.TwistValue.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
        self.readEncoderValues = channel.unary_stream(
            '/rosbridge_service.RosBridgeService/readEncoderValues',
            request_serializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.SerializeToString,
            response_deserializer=rosbridge__service__pb2.EncoderValue.FromString,
        )
        self.readCommandValues = channel.unary_stream(
            '/rosbridge_service.RosBridgeService/readCommandValues',
            request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            response_deserializer=rosbridge__service__pb2.CommandValue.FromString,
        )


class RosBridgeServiceServicer(object):

    def writeTwistValue(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def streamTwistValues(self, request_iterator, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def readEncoderValues(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def readCommandValues(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RosBridgeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'writeTwistValue': grpc.unary_unary_rpc_method_handler(
            servicer.writeTwistValue,
            request_deserializer=rosbridge__service__pb2.TwistValue.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
        'streamTwistValues': grpc.stream_unary_rpc_method_handler(
            servicer.streamTwistValues,
            request_deserializer=rosbridge__service__pb2.TwistValue.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
        'readEncoderValues': grpc.unary_stream_rpc_method_handler(
            servicer.readEncoderValues,
            request_deserializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.FromString,
            response_serializer=rosbridge__service__pb2.EncoderValue.SerializeToString,
        ),
        'readCommandValues': grpc.unary_stream_rpc_method_handler(
            servicer.readCommandValues,
            request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            response_serializer=rosbridge__service__pb2.CommandValue.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'rosbridge_service.RosBridgeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
