# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rosbridge_service.proto

import sys

_b = sys.version_info[0] < 3 and (lambda x: x) or (lambda x: x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2

from google.protobuf.empty_pb2 import *
from google.protobuf.wrappers_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
    name='rosbridge_service.proto',
    package='rosbridge_service',
    syntax='proto3',
    serialized_pb=_b(
        '\n\x17rosbridge_service.proto\x12\x11rosbridge_service\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\"{\n\nTwistValue\x12\x10\n\x08linear_x\x18\x01 \x01(\x01\x12\x10\n\x08linear_y\x18\x02 \x01(\x01\x12\x10\n\x08linear_z\x18\x03 \x01(\x01\x12\x11\n\tangular_x\x18\x04 \x01(\x01\x12\x11\n\tangular_y\x18\x05 \x01(\x01\x12\x11\n\tangular_z\x18\x06 \x01(\x01\"\x1d\n\x0c\x45ncoderValue\x12\r\n\x05value\x18\x01 \x01(\x01\"4\n\x0c\x43ommandValue\x12\x0f\n\x07\x63ommand\x18\x01 \x01(\t\x12\x13\n\x0b\x63ommand_arg\x18\x02 \x01(\t2\xd0\x02\n\x10RosBridgeService\x12H\n\x0fwriteTwistValue\x12\x1d.rosbridge_service.TwistValue\x1a\x16.google.protobuf.Empty\x12L\n\x11streamTwistValues\x12\x1d.rosbridge_service.TwistValue\x1a\x16.google.protobuf.Empty(\x01\x12T\n\x11readEncoderValues\x12\x1c.google.protobuf.StringValue\x1a\x1f.rosbridge_service.EncoderValue0\x01\x12N\n\x11readCommandValues\x12\x16.google.protobuf.Empty\x1a\x1f.rosbridge_service.CommandValue0\x01\x42\x15\n\x11org.athenian.grpcP\x01P\x00P\x01\x62\x06proto3')
    ,
    dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR, google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR, ],
    public_dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,
                         google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR, ])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_TWISTVALUE = _descriptor.Descriptor(
    name='TwistValue',
    full_name='rosbridge_service.TwistValue',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='linear_x', full_name='rosbridge_service.TwistValue.linear_x', index=0,
            number=1, type=1, cpp_type=5, label=1,
            has_default_value=False, default_value=float(0),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='linear_y', full_name='rosbridge_service.TwistValue.linear_y', index=1,
            number=2, type=1, cpp_type=5, label=1,
            has_default_value=False, default_value=float(0),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='linear_z', full_name='rosbridge_service.TwistValue.linear_z', index=2,
            number=3, type=1, cpp_type=5, label=1,
            has_default_value=False, default_value=float(0),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='angular_x', full_name='rosbridge_service.TwistValue.angular_x', index=3,
            number=4, type=1, cpp_type=5, label=1,
            has_default_value=False, default_value=float(0),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='angular_y', full_name='rosbridge_service.TwistValue.angular_y', index=4,
            number=5, type=1, cpp_type=5, label=1,
            has_default_value=False, default_value=float(0),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='angular_z', full_name='rosbridge_service.TwistValue.angular_z', index=5,
            number=6, type=1, cpp_type=5, label=1,
            has_default_value=False, default_value=float(0),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=107,
    serialized_end=230,
)


_ENCODERVALUE = _descriptor.Descriptor(
    name='EncoderValue',
    full_name='rosbridge_service.EncoderValue',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='value', full_name='rosbridge_service.EncoderValue.value', index=0,
            number=1, type=1, cpp_type=5, label=1,
            has_default_value=False, default_value=float(0),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=232,
    serialized_end=261,
)

_COMMANDVALUE = _descriptor.Descriptor(
    name='CommandValue',
    full_name='rosbridge_service.CommandValue',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
        _descriptor.FieldDescriptor(
            name='command', full_name='rosbridge_service.CommandValue.command', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
        _descriptor.FieldDescriptor(
            name='command_arg', full_name='rosbridge_service.CommandValue.command_arg', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=_b("").decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            options=None),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=263,
    serialized_end=315,
)

DESCRIPTOR.message_types_by_name['TwistValue'] = _TWISTVALUE
DESCRIPTOR.message_types_by_name['EncoderValue'] = _ENCODERVALUE
DESCRIPTOR.message_types_by_name['CommandValue'] = _COMMANDVALUE

TwistValue = _reflection.GeneratedProtocolMessageType('TwistValue', (_message.Message,), dict(
    DESCRIPTOR=_TWISTVALUE,
    __module__='rosbridge_service_pb2'
    # @@protoc_insertion_point(class_scope:rosbridge_service.TwistValue)
))
_sym_db.RegisterMessage(TwistValue)

EncoderValue = _reflection.GeneratedProtocolMessageType('EncoderValue', (_message.Message,), dict(
    DESCRIPTOR=_ENCODERVALUE,
    __module__='rosbridge_service_pb2'
    # @@protoc_insertion_point(class_scope:rosbridge_service.EncoderValue)
))
_sym_db.RegisterMessage(EncoderValue)

CommandValue = _reflection.GeneratedProtocolMessageType('CommandValue', (_message.Message,), dict(
    DESCRIPTOR=_COMMANDVALUE,
    __module__='rosbridge_service_pb2'
    # @@protoc_insertion_point(class_scope:rosbridge_service.CommandValue)
))
_sym_db.RegisterMessage(CommandValue)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\021org.athenian.grpcP\001'))
try:
    # THESE ELEMENTS WILL BE DEPRECATED.
    # Please use the generated *_pb2_grpc.py files instead.
    import grpc
    from grpc.framework.common import cardinality
    from grpc.framework.interfaces.face import utilities as face_utilities
    from grpc.beta import implementations as beta_implementations
    from grpc.beta import interfaces as beta_interfaces


    class RosBridgeServiceStub(object):

        def __init__(self, channel):
            """Constructor.

            Args:
              channel: A grpc.Channel.
            """
            self.writeTwistValue = channel.unary_unary(
                '/rosbridge_service.RosBridgeService/writeTwistValue',
                request_serializer=TwistValue.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            )
            self.streamTwistValues = channel.stream_unary(
                '/rosbridge_service.RosBridgeService/streamTwistValues',
                request_serializer=TwistValue.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            )
            self.readEncoderValues = channel.unary_stream(
                '/rosbridge_service.RosBridgeService/readEncoderValues',
                request_serializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.SerializeToString,
                response_deserializer=EncoderValue.FromString,
            )
            self.readCommandValues = channel.unary_stream(
                '/rosbridge_service.RosBridgeService/readCommandValues',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=CommandValue.FromString,
            )


    class RosBridgeServiceServicer(object):

        def writeTwistValue(self, request, context):
            context.set_code(grpc.StatusCode.UNIMPLEMENTED)
            context.set_details('Method not implemented!')
            raise NotImplementedError('Method not implemented!')

        def streamTwistValues(self, request_iterator, context):
            context.set_code(grpc.StatusCode.UNIMPLEMENTED)
            context.set_details('Method not implemented!')
            raise NotImplementedError('Method not implemented!')

        def readEncoderValues(self, request, context):
            context.set_code(grpc.StatusCode.UNIMPLEMENTED)
            context.set_details('Method not implemented!')
            raise NotImplementedError('Method not implemented!')

        def readCommandValues(self, request, context):
            context.set_code(grpc.StatusCode.UNIMPLEMENTED)
            context.set_details('Method not implemented!')
            raise NotImplementedError('Method not implemented!')


    def add_RosBridgeServiceServicer_to_server(servicer, server):
        rpc_method_handlers = {
            'writeTwistValue': grpc.unary_unary_rpc_method_handler(
                servicer.writeTwistValue,
                request_deserializer=TwistValue.FromString,
                response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'streamTwistValues': grpc.stream_unary_rpc_method_handler(
                servicer.streamTwistValues,
                request_deserializer=TwistValue.FromString,
                response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'readEncoderValues': grpc.unary_stream_rpc_method_handler(
                servicer.readEncoderValues,
                request_deserializer=google_dot_protobuf_dot_wrappers__pb2.StringValue.FromString,
                response_serializer=EncoderValue.SerializeToString,
            ),
            'readCommandValues': grpc.unary_stream_rpc_method_handler(
                servicer.readCommandValues,
                request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                response_serializer=CommandValue.SerializeToString,
            ),
        }
        generic_handler = grpc.method_handlers_generic_handler(
            'rosbridge_service.RosBridgeService', rpc_method_handlers)
        server.add_generic_rpc_handlers((generic_handler,))


    class BetaRosBridgeServiceServicer(object):
        """The Beta API is deprecated for 0.15.0 and later.

        It is recommended to use the GA API (classes and functions in this
        file not marked beta) for all further purposes. This class was generated
        only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""

        def writeTwistValue(self, request, context):
            context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)

        def streamTwistValues(self, request_iterator, context):
            context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)

        def readEncoderValues(self, request, context):
            context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)

        def readCommandValues(self, request, context):
            context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


    class BetaRosBridgeServiceStub(object):
        """The Beta API is deprecated for 0.15.0 and later.

        It is recommended to use the GA API (classes and functions in this
        file not marked beta) for all further purposes. This class was generated
        only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""

        def writeTwistValue(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
            raise NotImplementedError()

        writeTwistValue.future = None

        def streamTwistValues(self, request_iterator, timeout, metadata=None, with_call=False, protocol_options=None):
            raise NotImplementedError()

        streamTwistValues.future = None

        def readEncoderValues(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
            raise NotImplementedError()

        def readCommandValues(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
            raise NotImplementedError()


    def beta_create_RosBridgeService_server(servicer, pool=None, pool_size=None, default_timeout=None,
                                            maximum_timeout=None):
        """The Beta API is deprecated for 0.15.0 and later.

        It is recommended to use the GA API (classes and functions in this
        file not marked beta) for all further purposes. This function was
        generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
        request_deserializers = {
            ('rosbridge_service.RosBridgeService',
             'readCommandValues'): google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            ('rosbridge_service.RosBridgeService',
             'readEncoderValues'): google_dot_protobuf_dot_wrappers__pb2.StringValue.FromString,
            ('rosbridge_service.RosBridgeService', 'streamTwistValues'): TwistValue.FromString,
            ('rosbridge_service.RosBridgeService', 'writeTwistValue'): TwistValue.FromString,
        }
        response_serializers = {
            ('rosbridge_service.RosBridgeService', 'readCommandValues'): CommandValue.SerializeToString,
            ('rosbridge_service.RosBridgeService', 'readEncoderValues'): EncoderValue.SerializeToString,
            ('rosbridge_service.RosBridgeService',
             'streamTwistValues'): google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ('rosbridge_service.RosBridgeService',
             'writeTwistValue'): google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        }
        method_implementations = {
            ('rosbridge_service.RosBridgeService', 'readCommandValues'): face_utilities.unary_stream_inline(
                servicer.readCommandValues),
            ('rosbridge_service.RosBridgeService', 'readEncoderValues'): face_utilities.unary_stream_inline(
                servicer.readEncoderValues),
            ('rosbridge_service.RosBridgeService', 'streamTwistValues'): face_utilities.stream_unary_inline(
                servicer.streamTwistValues),
            ('rosbridge_service.RosBridgeService', 'writeTwistValue'): face_utilities.unary_unary_inline(
                servicer.writeTwistValue),
        }
        server_options = beta_implementations.server_options(request_deserializers=request_deserializers,
                                                             response_serializers=response_serializers,
                                                             thread_pool=pool, thread_pool_size=pool_size,
                                                             default_timeout=default_timeout,
                                                             maximum_timeout=maximum_timeout)
        return beta_implementations.server(method_implementations, options=server_options)


    def beta_create_RosBridgeService_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
        """The Beta API is deprecated for 0.15.0 and later.

        It is recommended to use the GA API (classes and functions in this
        file not marked beta) for all further purposes. This function was
        generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
        request_serializers = {
            ('rosbridge_service.RosBridgeService',
             'readCommandValues'): google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ('rosbridge_service.RosBridgeService',
             'readEncoderValues'): google_dot_protobuf_dot_wrappers__pb2.StringValue.SerializeToString,
            ('rosbridge_service.RosBridgeService', 'streamTwistValues'): TwistValue.SerializeToString,
            ('rosbridge_service.RosBridgeService', 'writeTwistValue'): TwistValue.SerializeToString,
        }
        response_deserializers = {
            ('rosbridge_service.RosBridgeService', 'readCommandValues'): CommandValue.FromString,
            ('rosbridge_service.RosBridgeService', 'readEncoderValues'): EncoderValue.FromString,
            ('rosbridge_service.RosBridgeService',
             'streamTwistValues'): google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            ('rosbridge_service.RosBridgeService',
             'writeTwistValue'): google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        }
        cardinalities = {
            'readCommandValues': cardinality.Cardinality.UNARY_STREAM,
            'readEncoderValues': cardinality.Cardinality.UNARY_STREAM,
            'streamTwistValues': cardinality.Cardinality.STREAM_UNARY,
            'writeTwistValue': cardinality.Cardinality.UNARY_UNARY,
        }
        stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer,
                                                         request_serializers=request_serializers,
                                                         response_deserializers=response_deserializers,
                                                         thread_pool=pool, thread_pool_size=pool_size)
        return beta_implementations.dynamic_stub(channel, 'rosbridge_service.RosBridgeService', cardinalities,
                                                 options=stub_options)
except ImportError:
    pass
# @@protoc_insertion_point(module_scope)
