# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import google.protobuf.empty_pb2 as google_dot_protobuf_dot_empty__pb2
import grpc

import rosbridge_service_pb2 as rosbridge__service__pb2


class RosBridgeServiceStub(object):

    def __init__(self, channel):
        """Constructor.

        Args:
          channel: A grpc.Channel.
        """
        self.writeTwistData = channel.unary_unary(
            '/rosbridge_service.RosBridgeService/writeTwistData',
            request_serializer=rosbridge__service__pb2.TwistData.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
        self.streamTwistData = channel.stream_unary(
            '/rosbridge_service.RosBridgeService/streamTwistData',
            request_serializer=rosbridge__service__pb2.TwistData.SerializeToString,
            response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
        )
        self.readEncoderData = channel.unary_stream(
            '/rosbridge_service.RosBridgeService/readEncoderData',
            request_serializer=rosbridge__service__pb2.EncoderDesc.SerializeToString,
            response_deserializer=rosbridge__service__pb2.EncoderData.FromString,
        )


class RosBridgeServiceServicer(object):

    def writeTwistData(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def streamTwistData(self, request_iterator, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def readEncoderData(self, request, context):
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RosBridgeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'writeTwistData': grpc.unary_unary_rpc_method_handler(
            servicer.writeTwistData,
            request_deserializer=rosbridge__service__pb2.TwistData.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
        'streamTwistData': grpc.stream_unary_rpc_method_handler(
            servicer.streamTwistData,
            request_deserializer=rosbridge__service__pb2.TwistData.FromString,
            response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
        ),
        'readEncoderData': grpc.unary_stream_rpc_method_handler(
            servicer.readEncoderData,
            request_deserializer=rosbridge__service__pb2.EncoderDesc.FromString,
            response_serializer=rosbridge__service__pb2.EncoderData.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'rosbridge_service.RosBridgeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
